#!/usr/bin/perl

use strict;
use warnings;

# The script that cleans the working directory from all files that were generated by GROMACS MD workflow

my $remove_com = 'rm \#*';
system $remove_com;

`rm *.log`;
`rm *.top`;
`rm *.gro`;
`rm temp.*`;
`rm *.xvg`;
`rm *.tpr`;
`rm *.itp`;
`rm *.edr`;
`rm *.trr`;
`rm *.cpt`;

